site_name: NeoGPT ðŸ¤–
docs_dir: 'content'
repo_url: https://github.com/neokd/NeoGPT
repo_name: neokd/NeoGPT
edit_uri: https://github.com/neokd/NeoGPT/tree/main/docs/content/
site_url: https://neokd.github.io/NeoGPT/
theme:
    name: material

    font:
      text: Nunito

    icon:
      repo: fontawesome/brands/github
      previous: fontawesome/solid/angle-left
      next: fontawesome/solid/angle-right
      logo: material/bookshelf
      admonition:
        note: fontawesome/solid/note-sticky
        abstract: fontawesome/solid/book
        info: fontawesome/solid/circle-info
        tip: fontawesome/solid/fire
        success: fontawesome/solid/check
        question: fontawesome/solid/circle-question
        warning: fontawesome/solid/triangle-exclamation
        failure: fontawesome/solid/bomb
        danger: fontawesome/solid/skull
        bug: fontawesome/solid/robot
        example: fontawesome/solid/flask
        quote: fontawesome/solid/quote-left
    features:
      - navigation.tabs
      - navigation.sections
      - search.share
      # - toc.integrate
      # - header.autohide
      - navigation.top
      - search.suggest
      - search.highlight
      - search.share
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
      - content.action.edit
      - navigation.footer
      - toc.follow
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
        primary: teal
        accent: teal
    # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
        primary: black
        accent: teal

nav:
  - Home: index.md
  - Docs:
    - Installation: installation.md
    - Builder: builder.md
    - Run NeoGPT: neogpt.md
    - Models:
        - Llama.cpp : models/llamacpp.md
        - Ollama: models/ollama.md
        - OpenAI: models/openai.md
    - Retrievers:
        - Local: retrievers/local.md
        - Web: retrievers/web.md
        - Hybrid: retrievers/hybrid.md
        - Contextual compression: retrievers/context.md
        - Stepback: retrievers/stepback.md
        - SQL : retrievers/sql.md
    - Persona: 
        - Persona & NeoGPT: persona/persona.md
        - Shell Persona: persona/shell.md
    - Agents: 
        - Agents & NeoGPT: agents/index.md
    - Settings:
        - Configure Search: advance/search.md
        - Configuration: advance/configuration.md
  - Developer's Guide:
      - Contributing: about/contributing.md
      - Code Of Conduct: about/code_of_conduct.md
      - Changelog: about/changelog.md

extra_css:
  - stylesheets/custom.css



markdown_extensions:
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

copyright: Copyright &copy; 2023 neokd

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/neokd/NeoGPT
      name: Github

    - icon:  fontawesome/brands/discord
      link: https://discord.gg/qNqjsGuCTG
      name: Discord
  generator: false
